#!/bin/bash

python wikiGSS.py       > 'wiki/gss.txt'
python wikiMGS.py -n99  > 'wiki/mgs.txt'
python wikiFG.py -n999  > 'wiki/fg.txt'
python wikiMGPG.py -n99 > 'wiki/mgpg.txt'
python wikiMYCPG.py -n99  > 'wiki/mycpg.txt'
python wikiMYCIGS.py -n99 > 'wiki/mycigs.txt'
python wikiLSIGS.py -n99  > 'wiki/lsigs.txt'
python wikiCalendar.py -s49 > 'wiki/calendar.txt'
python wikiCalendar.py -e48 -t'Results' > 'wiki/calendar.gs.txt'
python wikiCalendar.py -t'Results' > 'wiki/calendar.fsr.txt'

cat 'wiki/header.txt'   > 'wiki/out.txt'
cat 'wiki/mgs.txt'       >> 'wiki/out.txt'
cat 'wiki/fg.txt'        >> 'wiki/out.txt'
cat 'wiki/mgpg.txt'      >> 'wiki/out.txt'
cat 'wiki/mycpg.txt'     >> 'wiki/out.txt'
cat 'wiki/mycigs.txt'    >> 'wiki/out.txt'
cat 'wiki/lsigs.txt'     >> 'wiki/out.txt'
#cat 'wiki/calendar.txt'  >> 'wiki/out.txt'
cat 'wiki/footer.txt'    >> 'wiki/out.txt'

cat 'wiki/header.gs.txt'   > 'wiki/out.gs.txt'
cat 'wiki/gss.txt'          >> 'wiki/out.gs.txt'
cat 'wiki/calendar.gs.txt'  >> 'wiki/out.gs.txt'
cat 'wiki/footer.gs.txt'    >> 'wiki/out.gs.txt'

cat 'wiki/header.fsr.txt'   > 'wiki/out.fsr.txt'
cat 'wiki/gss.txt'           >> 'wiki/out.fsr.txt'
cat 'wiki/calendar.fsr.txt'  >> 'wiki/out.fsr.txt'
cat 'wiki/footer.fsr.txt'    >> 'wiki/out.fsr.txt'
