#!/usr/bin/python

whohas = { 'ALG' : u'Žužu' ,
           'ARG' : u'Míša' ,
           'AUS' : u'Petra' ,
           'BRA' : u'Dana' ,
           'CHI' : u'Hanka' ,
           'CIV' : u'Martin' ,
           'CMR' : u'Markéta' ,
           'DEN' : u'Martina' ,
           'ENG' : u'Hanka' ,
           'ESP' : u'Jana V.' ,
           'FRA' : u'Jana L.' ,
           'GER' : u'Lenny' ,
           'GHA' : u'Franta' ,
           'GRE' : u'Denisa' ,
           'HON' : u'Žužu' ,
           'ITA' : u'Jana V.' ,
           'JPN' : u'Standa' ,
           'KOR' : u'Vlasta' ,
           'MEX' : u'Olina H.' ,
           'NED' : u'Olina K.' ,
           'NGA' : u'Standa' ,
           'NZL' : u'Martin' ,
           'PAR' : u'Jana L.' ,
           'POR' : u'Eva' ,
           'PRK' : u'Martina' ,
           'RSA' : u'Wendy' ,
           'SRB' : u'Denisa' ,
           'SUI' : u'Renata Z.' ,
           'SVK' : u'Franta' ,
           'SVN' : u'Eva' ,
           'URU' : u'Renata Z.' ,
           'USA' : u'Tomáš' }
