#!/usr/bin/python

whohas = { 'ALG' : u'Ladislas von Meduna' ,
           'ARG' : u'Aaron Beck' ,
           'AUS' : u'Sir Aubrey Lewis' ,
           'BRA' : u'Michael Shepherd' ,
           'CHI' : u'Maxwell Jones' ,
           'CIV' : u'Richard von Krafft-Ebing' ,
           'CMR' : u'Ivan Pavlov' ,
           'DEN' : u'John Batty Tuke' ,
           'ENG' : u'W. H. R. Rivers' ,
           'ESP' : u'Wilfred Bion' ,
           'FRA' : u'Niall McLaren' ,
           'GER' : u'John Nemiah' ,
           'GHA' : u'Eugene Bleuler' ,
           'GRE' : u'Paul Watzlawick' ,
           'HON' : u'Eng Seong Tan' ,
           'ITA' : u'Alwyn Lishman' ,
           'JPN' : u'Ian Oswald' ,
           'KOR' : u'Norman Krietman' ,
           'MEX' : u'Karl Leonhard' ,
           'NED' : u'Eve Johnstone' ,
           'NGA' : u'Eugene Paykel' ,
           'NZL' : u'Elisabeth Kübler-Ross' ,
           'PAR' : u'Sigmund Freud' ,
           'POR' : u'Michael Rutter' ,
           'PRK' : u'Frantz Fanon' ,
           'RSA' : u'Kurt Schneider' ,
           'SRB' : u'Thomas Szasz' ,
           'SUI' : u'Arthur Kleinman' ,
           'SVK' : u'John Bowlby' ,
           'SVN' : u'Carl Gustav Jung' ,
           'URU' : u'John Cade' ,
           'USA' : u'Peter Sifneos' }
