#!/usr/bin/python

whohas = { 'ALG' : u'Martine' ,
           'ARG' : u'George' ,
           'AUS' : u'Sonia' ,
           'BRA' : u'Vendulka' ,
           'CHI' : u'Ailee' ,
           'CIV' : u'Quido' ,
           'CMR' : u'Lisa' ,
           'DEN' : u'Bas' ,
           'ENG' : u'George' ,
           'ESP' : u'Katka' ,
           'FRA' : u'Bas' ,
           'GER' : u'Harmen' ,
           'GHA' : u'AJ' ,
           'GRE' : u'Paul' ,
           'HON' : u'Sue' ,
           'ITA' : u'Rudy' ,
           'JPN' : u'Marty' ,
           'KOR' : u'Rudy' ,
           'MEX' : u'Sue' ,
           'NED' : u'Floris' ,
           'NGA' : u'Pippa' ,
           'NZL' : u'George' ,
           'PAR' : u'Martine' ,
           'POR' : u'Jens' ,
           'PRK' : u'Sonia' ,
           'RSA' : u'Scott' ,
           'SRB' : u'Olivia' ,
           'SUI' : u'Paul' ,
           'SVK' : u'Viktor' ,
           'SVN' : u'Jens' ,
           'URU' : u'AJ' ,
           'USA' : u'Harmen' }
